name: voice_synth
channels:
  - conda-forge
  - pytorch
dependencies:
  - nvidia-apex
  - python=3.8
  - matplotlib=2.1.0
  - tensorflow=1.15.2
  - numpy=1.13.3
  - inflect=0.2.5
  - librosa=0.6.0
  - scipy=1.0.0
  - Unidecode=1.0.22
  - pillow
  - azureml-core
  - pytorch=1.8=py38_cuda10.1_cudnn7.6.3_0
  - torchvision
  - torchaudio
  - cudatoolkit=10.1